### ISSUE TITLE
Schemas / Models

### ISSUE THREAD

**Issue by isabella-pettini** [uabcFinalProject/under-the-hood#7]

**Comment by iseanc** [comment]
- Renamed Maintenance model to ServiceItem.  Added "moreInfoLink" field, so we can link to educational material.
- Removed Owner from Vehicle (a User can have multiple vehicles)
- On Vehicle model, added fields for Reminders and ServiceHistory
- For Reminder, fields are now user, serviceType (link to ServiceItem), notifyStartDate, notifyFrequency, notifyType, and notes.
-
